### ISSUE TITLE
Doesn't work with react-native 0.6

### ISSUE THREAD

**Issue by owais** [umhan35/react-native-search-bar#3]
Trying to import this in react-native 0.6,

```
var SearchBar = require('react-native-search-bar');
```
results in the following error, 
![screen shot 2015-06-26 at 8 47 02 pm](https://cloud.githubusercontent.com/assets/46186/8380649/9116b092-1c44-11e5-8b9a-0a105f5ff598.png)

**Comment by owais** [comment]
I was able to solve this by removing react-native from react-native-search-bar node_modules. Like this,

```
rm -rf node_modules/react-native-search-bar/node_modules/react-native
```

The thing was crashing because react-native-saerch-bar had installed an older version of react-native inside it's node_modules even though another version was already present in the root node_modules.


Quite a few libraries do this. I think it makes sense to not mention react-native as a dependency at all. I think it is quite safe to assume that people would install react-native-search-bar only if they are using react-native already.

**Comment by umhan35** [comment]
Ah, I just pushed react-native-search-bar 0.0.7 to npm. After deleting `node_modules/react-native` and `node_modules/react-native-search-bar`, running 

```bash
npm install react-native@latest --save
npm install react-native-search-bar@latest --save
```

finally makes npm not download react-native inside `node_modules/react-native-search-bar`.

See this commit: 202f0016429360b01bd98d60b3c5f7db6b87e2ac.

I'm pretty sure the problem is solved not. Let me know if not :)
